# Generated by Django 4.2.1 on 2023-05-21 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applifting_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appliftingtoken",
            options={"get_latest_by": ["-created_at"]},
        ),
    ]
